AWSTemplateFormatVersion: 2010-09-09
Description: Data producer template
Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - "prod"
      - "dev"
      - "test"
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
  UserData:
    Type: String
  
Resources:
  # Data Producers Security Group
  DataProducerInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "DataProducerInstance-${Environment}"
      GroupDescription: Enable all traffic
      VpcId: !Sub "{{resolve:secretsmanager:VpcId-${Environment}}}"
      SecurityGroupIngress:
      - IpProtocol: -1
        CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: DataProducerInstance

  # EC2 instance for data producers
  DataProducerEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.small
      ImageId: ami-01cc34ab2709337aa
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref ManagedInstanceProfile
      NetworkInterfaces: 
      - AssociatePublicIpAddress: "true"
        DeviceIndex: "0"
        GroupSet: 
          - Ref: DataProducerInstanceSecurityGroup
        SubnetId: !Sub "{{resolve:secretsmanager:PublicSubnet2-${Environment}}}"
      Tags:
        - Key: Name
          Value: DataProducerInstance
      UserData:
        !Base64 |
        #!/bin/bash -xe
        exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
          yum -y update
          yum -y install git 
          amazon-linux-extras install docker -y
          usermod -a -G docker ec2-user
          systemctl start docker
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          python -m ensurepip --upgrade
          cd /home/ec2-user
          su ec2-user -c "git clone https://github.com/QuantumQuackDoctor/data-producers.git"
          cd data-producers/ && pip3 install -r requirements.txt
          python3 db/dbsetup.py
          python3 user_producer/generate_users.py
          python3 restaurant_producer/generate_restaurants.py
          python3 driver_producer/generate_drivers.py
          python3 food_order_producer/generate_orders.py
          cd pgadmin && docker-compose up -d

  ManagedInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - secretsmanager.amazonaws.com
            - ec2.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/SecretsManagerReadWrite
      Path: "/"

  ManagedInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - !Ref ManagedInstanceRole
      InstanceProfileName: ManagedInstanceProfile 

Outputs:
  DataProducerPublicIp:
    Description: EC2 Instance Public Ip
    Value: !GetAtt DataProducerEC2Instance.PublicIp